version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_USER: ${REGULAR_USER}
      MYSQL_PASSWORD: ${REGULAR_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - devdojo-db:/var/lib/mysql

volumes:
  devdojo-db:
