version: '3.8'

services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_USER: william
      MYSQL_PASSWORD: devdojo
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - devdojo-db:/var/lib/mysql

volumes:
  devdojo-db: