spring:
  application:
    name: anime-service

server:
  port: 8080
  servlet:
#    context-path: /${spring.application.name}
    context-path: /

logging:
  level:
    root: INFO
    academy.devdojo: INFO

database:
  url: localhost:3306
  username: mysql
  password: devdojo