spring:
  application:
    name: anime-service
  datasource:
    url: jdbc:mysql://localhost:3306/anime_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ROOT_USER:root}
    password: ${ROOT_PASSWORD:example}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
#    context-path: /${spring.application.name}
    context-path: /

logging:
  level:
    root: INFO
    academy.devdojo: INFO

management:
  server:
    port: 8989
  endpoints:
    web:
      exposure:
        include: "*"